### ISSUE TITLE
Use of extension mechanism

### ISSUE THREAD

**Issue by devoto13** [shouldjs/promised#4]
Hello,

Currently library extends core as a side-effect of `require`'ing it and also do `require('should')` inside without having dependency on it. Such way of extensibility generally considered as a bad practice.

We have [mechanism](https://github.com/shouldjs/should.js/blob/master/lib/should.js#L141) to extend `should` library already built in, it's excplicit and doesn't have side-effects of `require`'ing `should-promised`.

Do you think we can change current way to using the same way with `use()` as all built-in extensions use? If so, I can do it and send pull-request.

Best regards,
Yaroslav.

**Comment by btd** [comment]
Yes, sounds right. Need to change several things then:
1. Make this file to be function for `should.use`.
2. Make new main file which will auto extends `should` for npm, to do not break things.
3. Resolve util conflicts - either refactor to use should#throw in some way if possible (e.g create should#errorMatched or similar) or simply exports util to should.util (some of functions can be usefull for extensions) - i will accept both.

It will be very nice if you will think how better to use it in browser also (with should.js file that in root of should.js repo).

**Comment by dozoisch** [comment]
:+1:

**Comment by avimar** [comment]
I don't see how to use this!
When I require should-promised it works for the promises, but normal "should" features don't work.
How does this plugin work? Am I supposed to have them as two separate name spaces? Is there a way to use the should.use to "add" this?
