### ISSUE TITLE
promise.should.eventually.be.rejected throws with bluebird

### ISSUE THREAD

**Issue by wmertens** [shouldjs/promised#7]
See https://github.com/petkaantonov/bluebird/issues/493#issuecomment-133394132

Bluebird thinks that nothing is catching the exception when checking for rejected. I'm not sure I understand it but it would be great if .should.eventually.be.rejected works.

**Comment by btd** [comment]
I am not sure i understand how linked issue applies to should-promised. Can you please add more explanation and test case where it is working not like it should.

**Comment by wmertens** [comment]
Bluebird throws any uncaught rejections, and for some reason the handler that should-promised attaches doesn't count.

So this works as it should:

``` coffee
    makePromise()
    .then(
      -> throw new Error "bad"
      -> true
    )
```

but this gives an "Unhandled rejection Error":

``` coffee
    makePromise()
    .should.eventually.be.rejected
```

**Comment by btd** [comment]
Yes, that is right. You make a promise. Then you expect it to be rejected. If promise rejected, returned resolved promise. If promise resolved returned rejected promise, because you expected promise to be rejected, but was resolved.
You see unhandled promise (not unhandled exception), because result of .rejected() is Promise.

**Comment by wmertens** [comment]
Oh right now I understand. Is there a nice short way to write things so the
promise is still given to mocha but doesn't throw?

On Fri, Aug 21, 2015, 19:29 Denis Bardadym notifications@github.com wrote:

> Yes, that is right. You make a promise. Then you expect it to be rejected.
> If promise rejected, returned resolved promise. If promise resolved
> returned rejected promise, because you expected promise to be rejected, but
> was resolved.
> You see unhandled promise (not unhandled exception), because result of
> .rejected() is Promise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shouldjs/promised/issues/7#issuecomment-133504955.
> 
> ## 

Wout.
(typed on mobile, excuse terseness)

**Comment by btd** [comment]
You can return promise at the end of test function. But make sure you do not declare `done` callback.
Or you can in opposite add `done` callback and call it with .then.
Like

```
...rejected().then (done, done)
```

Also take a look at shouldjs repo wiki FAQ page contains examples. And look at tests in this repo.

**Comment by wmertens** [comment]
I figured it out, I had two problems:
- I was not calling `.rejected()` but just `.rejected` :expressionless: 
- I was using `.eventually` and that converted the promise to the value :sweat_smile: 

Thanks for your help!
